version: '3'
services:
  test:
    build:
      context: .
    command: npm test
    environment:
      NODE_ENV: development
    volumes:
      - .:/home/app/arbor
      - /home/app/arbor/node_modules
